version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - vibecode-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - vibecode-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - vibecode-network

  sandbox:
    build:
      context: ./docker
      dockerfile: Dockerfile.sandbox
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vibecode-network

networks:
  vibecode-network:
    driver: bridge
